language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
    - pip install python-coveralls nose mock unittest2
script:
    - nosetests --with-coverage --cover-erase --cover-package=bootstrap_vi
after_success:
    - coveralls
